### ISSUE TITLE
Adjust length of lines in `smoke_test.py`

### ISSUE THREAD

**Issue by ivan-podorozhnyi** [tatools/demo-python#16]
After #14 line in `smoke_test.py` became too long and pylint check throws non-zero exit code.
Task: adjust line length according to convention.

**Comment by extsoft** [comment]
@ivan-podorozhnyi what is flake's value for a length of a line?

**Comment by extsoft** [comment]
@ivan-podorozhnyi we have to configure it for 120 chars, if possible, otherwise skip this check.

**Comment by ivan-podorozhnyi** [comment]
@extsoft Maximum allowed default line length is 79. To configure it for 120 chars we will have to add configuration file to our project (setup.cfg, tox.ini, or .flake8). Flake8 can be also configured to use user global settings file from ~/.config/flake8 (or ~/.flake8 on Windows) but I don't think that's a good idea. 

Inside configuration file we must write:
```
[flake8]
max-line-length = 120
```
Please let me know which solution is ok for you.

**Comment by extsoft** [comment]
@ivan-podorozhnyi okay, let's create a configuration file (`.flake8`). We don't need to modify our code.

**Comment by ivan-podorozhnyi** [comment]
@extsoft Ok, I will add it.

**Comment by ivan-podorozhnyi** [comment]
@extsoft Created #19 according to your requirement.
