### ISSUE TITLE
Update configuration for flake8

### ISSUE THREAD

**Issue by extsoft** [tatools/demo-python#37]
Please use the following as default configuration for `flake8`:
```
[flake8]
max-complexity = 5
max-line-length = 120
statistics = True
count = True
```

Comments:
- `max-complexity` specifies how complex code could be (read https://en.wikipedia.org/wiki/Cyclomatic_complexity for the details)
- `max-line-length` is already present
- `statistics` means print general errors statistic
- `count` means how many violations we have

**Comment by vyahello** [comment]
@extsoft  PR [https://github.com/tatools/demo-python/pull/39](https://github.com/tatools/demo-python/pull/39) is opened regarding this issue.
