### ISSUE TITLE
Configure setup tools 

### ISSUE THREAD

**Issue by extsoft** [tatools/demo-python#4]
We need to be able to install this project as python dependency. Please use setup tools to achieve this. And look for https://github.com/ets-labs/python-dependency-injector as for an example.
Definitions of done:
- `demo_python_at` package is installed as `demo_at` package to the some Python
- update README with appropriate instructions
- configure Travis to install the package after `verify_project.sh`

**Comment by AntonKarabaza** [comment]
@extsoft Please, provide information that have to appear in `setup.py`.
Is `name, version, packages, install_requires` enough?

**Comment by extsoft** [comment]
@AntonKarabaza  I think we have to provide:
- version
- description
- long_description
- url
- install_requires
- packages
- license

**Comment by extsoft** [comment]
Done.
