### ISSUE TITLE
Configure pydocstyle

### ISSUE THREAD

**Issue by extsoft** [tatools/demo-python#7]
Add [pydocstyle](https://pypi.python.org/pypi/pydocstyle) to the project.
Definitions of done:
- pydocstyle is configured as a dev dependency
- pydocstyle is used in `verify_project.sh` after unit testing

Use https://github.com/ets-labs/python-dependency-injector as an example.

**Comment by AntonKarabaza** [comment]
@extsoft Are we have to check only `demo_python_at`package? And how `pydocstyle` have to be configured, because now there are a lot of violations of docstyle and `verify_project.sh` script won't finish with 0 exit code?

**Comment by extsoft** [comment]
@AntonKarabaza could you please provide the violations?

**Comment by AntonKarabaza** [comment]
@extsoft Here:
demo_python_at/__init__.py:1 at module level:
        D104: Missing docstring in public package
demo_python_at/commoms/__init__.py:1 at module level:
        D104: Missing docstring in public package
demo_python_at/commoms/application.py:1 at module level:
        D100: Missing docstring in public module
demo_python_at/commoms/application.py:7 in public class `Application`:
        D101: Missing docstring in public class
demo_python_at/commoms/application.py:9 in public method `print`:
        D102: Missing docstring in public method
demo_python_at/commoms/application.py:13 in public class `SimpleApplication`:
        D101: Missing docstring in public class
demo_python_at/commoms/application.py:14 in public method `__init__`:
        D102: Missing docstring in public method
demo_python_at/commoms/application.py:18 in public method `print`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:1 at module level:
        D100: Missing docstring in public module
demo_python_at/commoms/message.py:4 in public class `Message`:
        D101: Missing docstring in public class
demo_python_at/commoms/message.py:6 in public method `data`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:10 in public method `exist`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:14 in public class `StrMessage`:
        D101: Missing docstring in public class
demo_python_at/commoms/message.py:15 in public method `__init__`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:18 in public method `exist`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:21 in public method `data`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:25 in public class `HtmlMessage`:
        D101: Missing docstring in public class
demo_python_at/commoms/message.py:26 in public method `__init__`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:29 in public method `data`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:32 in public method `exist`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:36 in public class `FakeMessage`:
        D101: Missing docstring in public class
demo_python_at/commoms/message.py:37 in public method `__init__`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:41 in public method `exist`:
        D102: Missing docstring in public method
demo_python_at/commoms/message.py:44 in public method `data`:
        D102: Missing docstring in public method
demo_python_at/commoms/printer.py:1 at module level:
        D100: Missing docstring in public module
demo_python_at/commoms/printer.py:6 in public class `Printer`:
        D101: Missing docstring in public class
demo_python_at/commoms/printer.py:8 in public method `print`:
        D102: Missing docstring in public method
demo_python_at/commoms/printer.py:12 in public class `StdoutPrinter`:
        D101: Missing docstring in public class
demo_python_at/commoms/printer.py:13 in public method `print`:
        D102: Missing docstring in public method
demo_python_at/tests/__init__.py:1 at module level:
        D104: Missing docstring in public package
demo_python_at/tests/smoke_test.py:1 at module level:
        D100: Missing docstring in public module
demo_python_at/tests/smoke_test.py:6 in public function `test_foo`:
        D103: Missing docstring in public function

**Comment by extsoft** [comment]
@AntonKarabaza let's disable all `Missing docstring` checks. Error codes are [here](http://www.pydocstyle.org/en/latest/error_codes.html). Will these skipped rules allow to pass doc style check?

**Comment by AntonKarabaza** [comment]
@extsoft Done. Yes, they will. Now check is passed.

**Comment by AntonKarabaza** [comment]
@extsoft Do we need `.pydocstyle` configuration file? Now we have only one flag in `pydocstyle` invocation, but it might be useful in future to have all configurations in one file.

**Comment by extsoft** [comment]
@AntonKarabaza yes, please add.

**Comment by extsoft** [comment]
Done.
